pipeline {
  agent {
    docker {
      image 'node:12.14'
      args '-u node -m 1G -v /home/jenkins/.ssh:/home/node/.ssh'
    }

  }
  stages {
    stage('Install') {
      steps {
        dir(path: 'src/web') {
          sh 'npm install'
        }

      }
    }

    stage('Build') {
      steps {
        dir(path: 'src/web') {
          sh 'export NODE_OPTIONS=--max_old_space_size=1000 && npm run build'
        }

      }
    }

    stage('Publish') {
      steps {
        dir(path: 'src/web') {
          sh 'scp -r dist autojenkins@www.greatwebtech.cn:~/JAVA-Mysql'
        }

      }
    }

  }
}